Added support for running externally defined functions
jorenham/mainpy pull request #1
Opened 2023-07-14 23:07 UTC by wolph

2023-07-15 00:18 UTC, jorenham requested changes
Thanks for this! 
I added a couple of comments.

2023-07-15 00:18 UTC, jorenham commented on mainpy/__init__.py
> +        name = function.__module__
performance-wise it might be best to check if `function.__module__ == '__main__` , before traversing the call stack

2023-07-15 00:18 UTC, jorenham commented on tests/test_mainpy.py
> +    frame = sys._getframe(1).f_back  # noqa
Using `inspect.currentframe()` here should help with readability. Especially since the `import inspect` overhead isn't much of a issue, here.

2023-07-15 00:18 UTC, jorenham commented on README.md
> +It's also possible to run a main function from another module:
Since this PR effectively adds support for tools like `typer` and `click`, it might be cool to include a short example of that here as well.

2023-07-15 00:18 UTC, jorenham commented on mainpy/__init__.py
> +        name = frame.f_globals['__name__']
In e.g. REPL,  `__main__` might not be defined

2023-07-15 00:20 UTC, jorenham commented on mainpy/__init__.py
> +        name = frame.f_globals['__name__']
```
In [1]: globals()['__main__']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 1
----> 1 globals()['__main__']

KeyError: '__main__'
```

2023-07-16 18:16 UTC, jorenham requested changes

2023-07-16 18:16 UTC, jorenham commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
this looks like a rebase issue

2023-07-18 12:27 UTC, jorenham requested changes
Aside from the rebase issue, this looks good now 👌🏻

2023-07-18 12:59 UTC, wolph commented
I've re-merged the pyproject.toml. Apparently git f'ed up again :P

2023-07-18 14:23 UTC, merged